const KEY="poshan-mis-v1";
const VILLAGES={Palia:["Palia Khurd","Patihan","Farsaheya","Basantapur Kalan","Basantapur Khurd","Mujaha","Malineya","Bijauriya","Atariya","Majhara Paschim"],Nighasan:["Singahi Dehat","Daulatapur","Ballipur","Ramuwapur","Bamhanpur","Kharahani","Chakhara","Dubha","Bhairampur","Naugawan"],Dhaurahara:["Harsinghpur","Amethi","Dhaurahara-3","Dhaurahara-4","Dhaurahara-5","Dhaurahara-6","Dhaurahara-7","Dhaurahara-8","Dhaurahara-9","Dhaurahara-10"]};
const TARGETS={women:1500,children:1800,gardens:250,shg:18,camps:18,sessions:60};
function load(){const r=localStorage.getItem(KEY);if(r)return JSON.parse(r);return{users:[{id:"admin",name:"Coordinator",pin:"2026"}],session:null,women:[],children:[],sessions:[],sam:[],camps:[],gardens:[],shg:[],vouchers:[],training:[],timesheet:[],incidents:[]};}
function save(){localStorage.setItem(KEY,JSON.stringify(DB));}
let DB=load(),VIEW="dash";
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6);}
function val(id){return (document.getElementById(id)||{}).value||"";}
function opts(a){return a.map(v=>`<option>${v}</option>`).join("");}
function villageOpts(){return Object.entries(VILLAGES).map(([b,vs])=>`<optgroup label="${b}">${vs.map(v=>`<option>${v}</option>`).join("")}</optgroup>`).join("");}
function loginView(){return `<div class="login"><h2>Poshan Suraksha MIS</h2><p class="muted">CARD · AIC CSR · Phase 1</p><label>User</label><input id="u" value="admin"/><label>PIN</label><input id="p" type="password" value="2026"/><div class="actions"><button class="btn" onclick="doLogin()">Enter</button></div></div>`;}
function doLogin(){const u=DB.users.find(x=>x.id===val("u")&&x.pin===val("p"));if(!u){alert("Wrong PIN");return;}DB.session=u;save();render();}
function logout(){DB.session=null;save();render();}
function navBtn(id,l){return `<button class="${VIEW===id?"active":""}" onclick="go('${id}')">${l}</button>`;}
function go(id){VIEW=id;render();}
function shell(inner){return `<aside class="side"><div class="brand"><h1>POSHAN MIS</h1><p>Palia · Nighasan · Dhaurahara</p></div><nav><div class="sec">Overview</div>${navBtn("dash","Dashboard")}${navBtn("monthly","Monthly AIC sheet")}<div class="sec">Registers</div>${navBtn("women","Women")}${navBtn("children","Children / MUAC")}${navBtn("sam","SAM")}${navBtn("sessions","Sessions")}${navBtn("camps","Camps")}${navBtn("gardens","Gardens")}${navBtn("shg","SHG")}${navBtn("vouchers","Referral")}</nav></aside><section class="main">${inner}</section>`;}
function stat(n,t,l){return `<div class="stat"><b>${n} / ${t}</b><span>${l}</span></div>`;}
function table(h,rows){if(!rows.length)return `<p class="muted">No rows yet.</p>`;return `<table><thead><tr>${h.map(x=>`<th>${x}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??""}</td>`).join("")}</tr>`).join("")}</tbody></table>`;}
function formCard(t,f,fn){return `<div class="card"><h3>${t}</h3><div class="row">${f}</div><div class="actions"><button class="btn" onclick="${fn}">Save</button></div></div>`;}
function tag(col){const k=col==="Red"?"red":col==="Yellow"?"yel":"grn";return `<span class="tag ${k}">${col}</span>`;}
function dash(){return `<div class="top"><div><h2>Dashboard</h2></div><button class="btn ghost" onclick="logout()">Lock</button></div><div class="banner">Supported under CSR of <strong>AIC of India Ltd.</strong></div><div class="grid">${stat(DB.women.length,TARGETS.women,"Women")}${stat(DB.children.length,TARGETS.children,"Children")}${stat(DB.sessions.length,TARGETS.sessions,"Sessions")}${stat(DB.camps.length,TARGETS.camps,"Camps")}${stat(DB.gardens.length,TARGETS.gardens,"Gardens")}${stat(DB.shg.length,TARGETS.shg,"SHG")}</div>`;}
function womenView(){return `<div class="top"><h2>Women</h2></div>`+formCard("Add",`<div><label>Name</label><input id="w_name"></div><div><label>Village</label><select id="w_vil">${villageOpts()}</select></div><div><label>Status</label><select id="w_st"><option>Pregnant</option><option>Lactating</option></select></div><div><label>Phone</label><input id="w_ph"></div>`,"addWoman()")+`<div class="card">${table(["Name","Village","Status","Phone"],DB.women.map(w=>[w.name,w.village,w.status,w.phone]))}</div>`;}
function addWoman(){DB.women.push({name:val("w_name"),village:val("w_vil"),status:val("w_st"),phone:val("w_ph")});save();render();}
function childrenView(){return `<div class="top"><h2>Children / MUAC</h2></div>`+formCard("Screen",`<div><label>Child</label><input id="c_name"></div><div><label>Village</label><select id="c_vil">${villageOpts()}</select></div><div><label>MUAC mm</label><input id="c_muac" type="number"></div>`,"addChild()")+`<div class="card">${table(["Child","Village","MUAC","Colour"],DB.children.map(c=>[c.name,c.village,c.muac,tag(c.colour)]))}</div>`;}
function addChild(){const mu=+val("c_muac");const col=mu&&mu<115?"Red":mu&&mu<125?"Yellow":"Green";DB.children.push({name:val("c_name"),village:val("c_vil"),muac:mu,colour:col});if(col!=="Green")DB.sam.push({child:val("c_name"),village:val("c_vil"),colour:col,opened:new Date().toISOString().slice(0,10),reached72:"",outcome:""});save();render();}
function samView(){return `<div class="top"><h2>SAM follow-up</h2></div><div class="card">${table(["Child","Village","Colour","Opened"],DB.sam.map(s=>[s.child,s.village,tag(s.colour),s.opened]))}</div>`;}
function sessionsView(){return `<div class="top"><h2>Sessions</h2></div>`+formCard("Log",`<div><label>Date</label><input id="s_date" type="date"></div><div><label>Village</label><select id="s_vil">${villageOpts()}</select></div><div><label>Women</label><input id="s_n" type="number"></div>`,"addSession()")+`<div class="card">${table(["Date","Village","Women"],DB.sessions.map(s=>[s.date,s.village,s.n]))}</div>`;}
function addSession(){DB.sessions.push({date:val("s_date"),village:val("s_vil"),n:val("s_n")});save();render();}
function campsView(){return `<div class="top"><h2>Camps</h2></div>`+formCard("Camp",`<div><label>Date</label><input id="k_date" type="date"></div><div><label>Block</label><select id="k_block">${opts(Object.keys(VILLAGES))}</select></div>`,"addCamp()")+`<div class="card">${table(["Date","Block"],DB.camps.map(k=>[k.date,k.block]))}</div>`;}
function addCamp(){DB.camps.push({date:val("k_date"),block:val("k_block")});save();render();}
function gardensView(){return `<div class="top"><h2>Gardens</h2></div>`+formCard("Garden",`<div><label>HH</label><input id="g_name"></div><div><label>Village</label><select id="g_vil">${villageOpts()}</select></div>`,"addGarden()")+`<div class="card">${table(["HH","Village"],DB.gardens.map(g=>[g.name,g.village]))}</div>`;}
function addGarden(){DB.gardens.push({name:val("g_name"),village:val("g_vil")});save();render();}
function shgView(){return `<div class="top"><h2>SHG</h2></div>`+formCard("SHG",`<div><label>Name</label><input id="h_name"></div><div><label>Block</label><select id="h_block">${opts(Object.keys(VILLAGES))}</select></div>`,"addShg()")+`<div class="card">${table(["SHG","Block"],DB.shg.map(h=>[h.name,h.block]))}</div>`;}
function addShg(){DB.shg.push({name:val("h_name"),block:val("h_block")});save();render();}
function vouchersView(){return `<div class="top"><h2>Referral</h2></div>`+formCard("Voucher",`<div><label>Patient</label><input id="v_name"></div><div><label>Village</label><select id="v_vil">${villageOpts()}</select></div><div><label>Rs</label><input id="v_pa" type="number"></div>`,"addVoucher()")+`<div class="card">${table(["Patient","Village","Rs"],DB.vouchers.map(v=>[v.name,v.village,v.passed]))}</div>`;}
function addVoucher(){DB.vouchers.push({name:val("v_name"),village:val("v_vil"),passed:val("v_pa")});save();render();}
function monthlyView(){return `<div class="top"><h2>AIC monthly sheet</h2><button class="btn gold" onclick="window.print()">Print</button></div><div class="card">${table(["Indicator","Count","Bar"],[["Women",DB.women.length,1500],["Children",DB.children.length,1800],["Sessions",DB.sessions.length,60],["Camps",DB.camps.length,18],["Gardens",DB.gardens.length,250],["SHG",DB.shg.length,18]])}</div>`;}
const VIEWS={dash,women:womenView,children:childrenView,sam:samView,sessions:sessionsView,camps:campsView,gardens:gardensView,shg:shgView,vouchers:vouchersView,monthly:monthlyView};
function render(){const root=document.getElementById("root");if(!DB.session){root.className="";root.innerHTML=loginView();return;}root.className="app";root.innerHTML=shell(VIEWS[VIEW]());}
window.go=go;window.doLogin=doLogin;window.logout=logout;window.addWoman=addWoman;window.addChild=addChild;window.addSession=addSession;window.addCamp=addCamp;window.addGarden=addGarden;window.addShg=addShg;window.addVoucher=addVoucher;render();
